### PR TITLE
AndroRAT

### PR DESCRIPTION
**Pull request by MaryJ0420**
Android Remote Administrator

### CODE REVIEW

**Comment by Krazijay** [comment]
1fgrhj

**Comment by Sudharshan0207** [comment]
image
Resolve this for me

**Comment by preshy112** [comment]
hi Karma Master im a newbie here i will like to come under your tutorship, please reply this ....

**Review by ImFelixprogram — COMMENTED** [review]
This pull request doesn't add anything valuable, why did you open that?

**Review by najmulsheik — COMMENTED** [review]
Echo

**Comment by najmulsheik** [comment]
patch

**Review by Mensei163 — APPROVED** [review]

**Comment by Cyberwizardking** [comment]
Love

**Pull request closed without merging**
